name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0'

env: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup Golang environment
        uses: actions/setup-go@v4
      - name: Run test
        run: |
          go list -m | xargs go test

  versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19.4']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run test
        run: |
          go list -m | xargs go run

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup Golang environment
        uses: actions/setup-go@v4
      - name: Run cargo fmt
        run: |
          go list -m | xargs gofmt -e
